version: '3.9'

networks:
  networkFE:
  
services:
  frontend:
    build: 
      context: ./FronEnd
    ports:
      - 5050:5050
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: vip
      placements:
        constraints:
          - "node.role==worker"
        max_replicas_per_node: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 100s
